---
title: "code.qmd"
author: "Kyra Baranick"
format: html
editor: visual
---

[My GitHub Repository](baranickkyra/ENVS-193DS_homework-03: Homework Three for ENVS193DS)

```{r}
library(tidyverse)
library(here)
library(janitor)
library(readxl)

salinity <- read.csv(here("data","salinity-pickleweed.csv"))
Kyra_data <- read.csv(here("data","personal_data.csv"))

```

# Problem 1

### a. 

I could do a linear regression test or a Pearson's correlation test. Pearson’s correlation measures the stregeth and direction of a linear association between the two variables, while linear regression quantifies the relationship (1 predictor and 1 response) by estimating how biomass changes with salinity (uses slope and intercept).

### b. 

```{r}
ggplot(salinity, aes(x = salinity_mS_cm, y = pickleweed)) +
  geom_point(color = "darkorange") +
  geom_smooth(method = "lm", se = TRUE, color = "steelblue") +
  labs(
    x = "Soil salinity (mS/cm)",
    y = "Pickleweed biomass (g)",
    title = "Relationship between soil salinity and pickleweed biomass"
  ) +
  theme_minimal()

```

### c. 
